[build]
  # Command to build the frontend files (if needed) and start the backend server
  command = "npm run build && npm start"

  # Directory where your frontend files are located
  publish = "public" # Replace "public" with the directory containing your frontend files