[build]
  publish = "public"        # Your publish directory for static files
  functions = "functions"   # Directory containing Netlify Functions, if any
#  command = "npm run build" #Your build command, if needed
#
#[dev]
#  command = "npm run dev"   # Your development server command

