[build]
  # Command to start the backend server and build the frontend files (if needed)
  command = "npm start && npm run build"

  # Directory where your frontend files are located
  publish = "public" # Replace "public" with the directory containing your frontend files