[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 3000

[[headers]]
  for = "/api/rss"
  [headers.values]
    Content-Type = "text/xml"